### ISSUE TITLE
New HA 2022.4.5 API breaks integration

### ISSUE THREAD

**Issue by letovlive** [49jan/hass-ecovent#1]
HA introduced changes to the API where were deleted several constants.
https://github.com/home-assistant/core/commit/7fbe1dbc99b7cdf503820d2d0356090766ae1f7e

@49jan Do you have any plans to update your integration?

**Comment by 49jan** [comment]
Thanks for your feedback.

I am currently busy with some projects. I expect to prepare the update for HA 2022.4.5 in 2 weeks.

**Comment by 49jan** [comment]
@letovlive Version [1.1](https://github.com/49jan/hass-ecovent/releases/tag/1.1) should also work with the newer HA version.
